# gui build
FROM node:21.7-alpine as nodejs

WORKDIR /app
COPY . .

WORKDIR /app/gui
RUN npm i -g pnpm
RUN pnpm i
RUN pnpm build:stage

# run
FROM nginx:1.25.4
WORKDIR /app

COPY --from=nodejs /app/gui/dist /app/gui

COPY ./docker/assets/nginx/nginx-global-base.conf /etc/nginx/nginx.conf
COPY ./docker/assets/nginx/nginx-https-base.conf /app/nginx/nginx-https-base.conf
COPY ./docker/assets/nginx/nginx-server.conf /app/nginx/nginx-server.conf
COPY ./docker/secret/fullchain.pem /app/secret/fullchain.pem
COPY ./docker/secret/privkey.pem /app/secret/privkey.pem
